name: Run tooling on pr

on:
  pull_request:
    branches:
      - 'main'

jobs:
  call-lint-workflow:
    uses: ./.github/workflows/lint-code.yaml

  call-build-push-workflow:
    needs: call-lint-workflow
    uses: ./.github/workflows/build-push.yaml
    with:
      ENVIRONMENT: production
    secrets: inherit
      #DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
      #DISCORD_BOT_PUBLIC_KEY: ${{ secrets.DISCORD_BOT_PUBLIC_KEY }}
      #DISCORD_BOT_APPLICATION_ID: ${{ secrets.DISCORD_BOT_APPLICATION_ID }}

      # MongoDB
      #MONGODB_PREFIX: ${{ secrets.MONGODB_PREFIX }}
      #MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      #MONGODB_PASS: ${{ secrets.MONGODB_PASS }}
      #MONGODB_CLUSTER: ${{ secrets.MONGODB_CLUSTER }}

      # Sentry
      #SENTRY_IO_DSN: ${{ secrets.SENTRY_IO_DSN }}

      # Digital Ocean
      #DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  call-deploy-workflow:
    needs: call-build-push-workflow
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit